name: mdc_web
description: Material Design Component (MDC) for Dart.
version: 0.0.1-alpha

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  built_collection: ^4.0.0
  js: ^0.6.1
  path: ^1.6.0
  sass_builder: ^2.0.2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
